import { ArrowLeft, Edit3, Film, Play, Plus, Save, Users, WandSparkles } from 'lucide-react'
import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { Link, useParams } from 'react-router-dom'
import { LoadingScreen, PageHeader } from '../components/Page'
import { StatusBadge } from '../components/StatusBadge'
import { api } from '../lib/api'
import type { Character, Project, Shot } from '../types'

const engines: Record<string,string>={wan_s2v:'Wan2.2 S2V',echo_mimic:'EchoMimic V3',musetalk:'MuseTalk',camera_motion:'靜態運鏡'}

type Tab='shots'|'characters'|'source'
export function ProjectDetailPage(){
  const{id}=useParams();const[project,setProject]=useState<Project|null>(null);const[tab,setTab]=useState<Tab>('shots');const[showAdd,setShowAdd]=useState(false);const[editing,setEditing]=useState<Shot|null>(null);const[busy,setBusy]=useState(false)
  const load=useCallback(()=>api<Project>(`/api/projects/${id}`).then(setProject),[id])
  useEffect(()=>{void load();const timer=setInterval(()=>{if(tab==='shots')void load()},3000);return()=>clearInterval(timer)},[load,tab])
  if(!project)return <LoadingScreen/>
  async function queue(shotId:string){setBusy(true);try{await api(`/api/shots/${shotId}/queue`,{method:'POST'});await load()}finally{setBusy(false)}}
  async function queueAll(){setBusy(true);try{await api(`/api/projects/${id}/queue`,{method:'POST'});await load()}finally{setBusy(false)}}
  return <><Link to="/projects" className="mb-4 inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/>返回作品</Link><PageHeader title={project.title} description={`${project.shots.length}個分鏡 · ${project.characters.length}個角色`} action={<button className="btn-primary" disabled={busy||!project.shots.length} onClick={()=>void queueAll()}><WandSparkles size={17}/>生成全部分鏡</button>}/>
    <div className="mb-6 flex gap-1 overflow-x-auto rounded-xl border bg-white p-1">{([['shots','分鏡'],['characters','角色'],['source','小說原文']] as [Tab,string][]).map(([key,label])=><button key={key} onClick={()=>setTab(key)} className={`whitespace-nowrap rounded-lg px-4 py-2 text-sm font-semibold ${tab===key?'bg-slate-900 text-white':'text-slate-500 hover:bg-slate-50'}`}>{label}</button>)}</div>
    {tab==='shots'&&<><div className="mb-4 flex justify-end"><button className="btn-secondary" onClick={()=>setShowAdd(!showAdd)}><Plus size={16}/>新增分鏡</button></div>{showAdd&&<ShotForm projectId={project.id} onDone={async()=>{setShowAdd(false);await load()}}/>}<div className="space-y-4">{project.shots.map(shot=><article key={shot.id} className="card overflow-hidden"><div className="grid gap-0 lg:grid-cols-[280px_1fr]"><div className="relative grid min-h-44 place-items-center bg-slate-950 text-slate-500">{shot.output_url?<video className="h-full w-full object-cover" src={shot.output_url} controls preload="metadata"/>:<><Film size={34}/><span className="absolute left-3 top-3 rounded bg-black/60 px-2 py-1 text-xs text-white">SHOT {String(shot.sequence).padStart(2,'0')}</span></>}</div><div className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-bold">{shot.title}</h2><StatusBadge status={shot.status}/></div><p className="mt-1 text-xs font-medium text-blue-600">{engines[shot.engine]??shot.engine} · {shot.duration_seconds}秒</p></div><div className="flex gap-2"><button className="btn-secondary px-3" onClick={()=>setEditing(editing?.id===shot.id?null:shot)}><Edit3 size={15}/>編輯</button><button className="btn-primary px-3" disabled={busy||shot.status==='queued'||shot.status==='running'} onClick={()=>void queue(shot.id)}><Play size={15}/>{shot.status==='completed'?'重抽':'生成'}</button></div></div>{editing?.id===shot.id?<EditShotForm shot={editing} onDone={async()=>{setEditing(null);await load()}}/>:<div className="mt-5 grid gap-4 sm:grid-cols-2"><div><p className="label">畫面Prompt</p><p className="text-sm leading-6 text-slate-600">{shot.prompt||'未設定'}</p></div><div><p className="label">對白</p><p className="text-sm leading-6 text-slate-600">{shot.dialogue?`「${shot.dialogue}」`:'無對白'}</p></div></div>}</div></div></article>)}</div></>}
    {tab==='characters'&&<CharactersTab projectId={project.id} characters={project.characters} onDone={load}/>} {tab==='source'&&<SourceTab project={project} onDone={load}/>}</>
}

function ShotForm({projectId,onDone}:{projectId:string;onDone:()=>Promise<void>}){const[form,setForm]=useState({title:'',prompt:'',dialogue:'',duration_seconds:3,engine:'wan_s2v'});async function submit(e:FormEvent){e.preventDefault();await api(`/api/projects/${projectId}/shots`,{method:'POST',body:JSON.stringify(form)});await onDone()}return <form onSubmit={e=>void submit(e)} className="card mb-5 grid gap-4 p-5 lg:grid-cols-2"><div><label className="label">鏡頭名稱</label><input className="field" required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="label">引擎</label><select className="field" value={form.engine} onChange={e=>setForm({...form,engine:e.target.value})}>{Object.entries(engines).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></div><div><label className="label">秒數</label><input className="field" type="number" min="1" max="20" step="0.5" value={form.duration_seconds} onChange={e=>setForm({...form,duration_seconds:Number(e.target.value)})}/></div></div><div><label className="label">畫面Prompt</label><textarea className="field min-h-24" value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})}/></div><div><label className="label">對白</label><textarea className="field min-h-24" value={form.dialogue} onChange={e=>setForm({...form,dialogue:e.target.value})}/></div><div className="lg:col-span-2"><button className="btn-primary"><Plus size={16}/>加入分鏡</button></div></form>}

function EditShotForm({shot,onDone}:{shot:Shot;onDone:()=>Promise<void>}){const[form,setForm]=useState({...shot});async function save(){await api(`/api/shots/${shot.id}`,{method:'PATCH',body:JSON.stringify({title:form.title,prompt:form.prompt,dialogue:form.dialogue,duration_seconds:form.duration_seconds,engine:form.engine})});await onDone()}return <div className="mt-5 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-2"><input className="field" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><div className="grid grid-cols-2 gap-2"><select className="field" value={form.engine} onChange={e=>setForm({...form,engine:e.target.value})}>{Object.entries(engines).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><input className="field" type="number" value={form.duration_seconds} onChange={e=>setForm({...form,duration_seconds:Number(e.target.value)})}/></div><textarea className="field min-h-20" value={form.prompt} onChange={e=>setForm({...form,prompt:e.target.value})}/><textarea className="field min-h-20" value={form.dialogue} onChange={e=>setForm({...form,dialogue:e.target.value})}/><button className="btn-primary sm:col-span-2 sm:justify-self-start" onClick={()=>void save()}><Save size={15}/>儲存修改</button></div>}

function CharactersTab({projectId,characters,onDone}:{projectId:string;characters:Character[];onDone:()=>Promise<void>}){const[form,setForm]=useState({name:'',description:'',voice:'zh-HK-HiuGaaiNeural'});async function submit(e:FormEvent){e.preventDefault();await api(`/api/projects/${projectId}/characters`,{method:'POST',body:JSON.stringify(form)});setForm({...form,name:'',description:''});await onDone()}return <div className="grid gap-6 xl:grid-cols-[.65fr_1.35fr]"><form className="card h-fit space-y-4 p-5" onSubmit={e=>void submit(e)}><h2 className="font-semibold">新增角色</h2><div><label className="label">名稱</label><input className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></div><div><label className="label">外觀及性格</label><textarea className="field min-h-24" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div><label className="label">固定聲線</label><select className="field" value={form.voice} onChange={e=>setForm({...form,voice:e.target.value})}><option value="zh-HK-HiuGaaiNeural">HiuGaai（女）</option><option value="zh-HK-WanLungNeural">WanLung（男）</option><option value="zh-HK-HiuMaanNeural">HiuMaan（旁白）</option></select></div><button className="btn-primary"><Users size={16}/>加入角色</button></form><div className="grid gap-4 sm:grid-cols-2">{characters.map(c=><div className="card p-5" key={c.id}><div className="mb-4 grid h-12 w-12 place-items-center rounded-full bg-blue-50 font-bold text-blue-700">{c.name.slice(0,1)}</div><h3 className="font-bold">{c.name}</h3><p className="mt-1 text-xs text-blue-600">{c.voice}</p><p className="mt-3 text-sm leading-6 text-slate-500">{c.description||'尚未加入角色描述'}</p></div>)}</div></div>}

function SourceTab({project,onDone}:{project:Project;onDone:()=>Promise<void>}){const[source,setSource]=useState(project.source_text);async function save(){await api(`/api/projects/${project.id}`,{method:'PATCH',body:JSON.stringify({source_text:source})});await onDone()}return <section className="card p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">小說原文</h2><p className="mt-1 text-xs text-slate-500">稍後可接LLM自動拆解成分鏡</p></div><button className="btn-primary" onClick={()=>void save()}><Save size={15}/>儲存</button></div><textarea className="field min-h-[55vh] font-serif leading-8" value={source} onChange={e=>setSource(e.target.value)}/></section>}
