FROM python:3.11-slim-bookworm
RUN pip install --no-cache-dir runpod==1.8.1
WORKDIR /app
COPY models.json populate_volume.py volume_populator_handler.py ./
CMD ["python", "-u", "/app/volume_populator_handler.py"]
